users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users.views import (
    UserAuthView,
    user_details,
    user_signup,
    user_login,
    user_logout,
)
app_name= "users"

urlpatterns = [
    path("", user_login, name="login_page"),
    path("user/<int:id>", user_details, name="user_details"),
    path("signup-page/", user_signup, name="signup_page"),
    path("logout/", user_logout, name="logout"),
    path("password_reset/", auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"), name="password_reset"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name="password_reset_confirm"),
    path("password_reset_complete/", auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name="password_reset_complete"),
    path("signup/", UserAuthView.as_view({"post": "register"})),
    path(
        "send-otp/",
        UserAuthView.as_view({"post": "send_otp"}),
    ),
    path("verify-otp/", UserAuthView.as_view({"post": "verify_otp"})),
    path(
        "request-reset-email/",
        UserAuthView.as_view({"post": "send_password_reset_email"}),
        name="request-password-reset",
    ),
    path(
        "password-rest/<uidb64>/<token>/",
        UserAuthView.as_view({"post": "reset_password"}),
        name="password-reset-confirm",
    ),
]

vms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('dashboard/', include('venues.urls')),
    path('api-auth/', include('rest_framework.urls'), name='rest_framework'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Base(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class User(AbstractUser):
    name = models.CharField(max_length=150, null=True, blank=True)
    email = models.EmailField(_("email address"), blank=True, null=True, unique=True)
    mobile = models.CharField(max_length=15, unique=True)
    profile_image = models.ImageField(upload_to="profile/", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "User"
        verbose_name_plural = verbose_name

    def __str__(self) -> str:
        return self.username

    def get_absolute_url(self):
        return reverse("user_details", kwargs={"id": self.id})


class Otp(Base):
    email = models.EmailField(
        blank=True,
        null=True,
    )
    mobile = models.CharField(max_length=15, null=True, blank=True)
    otp = models.PositiveIntegerField(default=1111)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self) -> str:
        return f"{self.mobile}"

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "mobile", "password1", "password2"]

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.username = self.cleaned_data["username"]
        user.email = self.cleaned_data["email"]
        user.password = self.cleaned_data["password1"]
        user.mobile = self.cleaned_data["mobile"]
        if commit:
            user.save()
        else:
            print("ERROR")
        return user

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from rest_framework import viewsets, generics
from rest_framework import status
from rest_framework.response import Response
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.utils.encoding import (
    smart_str,
    force_str,
    smart_bytes,
    DjangoUnicodeDecodeError,
)
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import User, Otp
from .utils import send_reset_password_email
from .utils import (
    validate_data,
    register_user,
    is_mobile,
    send_sms,
    get_tokens_for_user,
)

from .forms import *


# Create your views here.
class UserAuthView(viewsets.ViewSet):
    authentication_classes = ()
    permission_classes = ()

    def register(self, request):
        try:
            data = request.data
            validate, msg = validate_data(data)
            if validate:
                user = register_user(data)
                if not user:
                    return Response(
                        data={"status": False, "message": "User already exists"},
                        status=status.HTTP_400_BAD_REQUEST,
                    )

                return Response(
                    data={
                        "status": validate,
                        "message": msg,
                    },
                    status=status.HTTP_200_OK,
                )
            else:
                return Response(
                    data={
                        "status": validate,
                        "message": msg,
                    },
                    status=status.HTTP_400_BAD_REQUEST,
                )
        except Exception as e:
            return Response(
                data={
                    "status": False,
                    "message": str(e),
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

    def send_otp(self, request):
        """SEND OTP"""
        try:
            mobile = request.data.get("mobile", None)
            if mobile:
                mobile = mobile.strip()
                if is_mobile(mobile):
                    if User.objects.filter(mobile=mobile).exists():
                        send_sms(mobile)
                        return Response(
                            data={"status": True, "message": str(mobile)},
                            status=status.HTTP_200_OK,
                        )
                    else:
                        return Response(
                            data={
                                "status": False,
                                "message": "No account found!",
                            },
                            status=status.HTTP_400_BAD_REQUEST,
                        )
                else:
                    return Response(
                        data={
                            "status": False,
                            "message": "Invalid mobile number",
                        },
                        status=status.HTTP_400_BAD_REQUEST,
                    )
            else:
                return Response(
                    data={
                        "status": False,
                        "message": "Invalid mobile number",
                    },
                    status=status.HTTP_400_BAD_REQUEST,
                )
        except Exception as e:
            return Response(
                data={
                    "status": False,
                    "message": str(e),
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

    def verify_otp(self, request):
        """LOGIN with OTP"""
        try:
            mobile = request.data.get("mobile")
            otp = request.data.get("otp")
            if mobile and otp:
                mobile = mobile.strip()
                otp = otp.strip()
                if Otp.objects.filter(mobile=mobile).exists():
                    instance = Otp.objects.filter(mobile=mobile).last()
                    if instance.otp == int(otp):
                        user = User.objects.get(mobile=mobile)
                        token = get_tokens_for_user(user)
                        return Response(
                            data={
                                "status": True,
                                "message": "Correct OTP",
                                "token": token,
                            },
                            status=status.HTTP_200_OK,
                        )
                    else:
                        return Response(
                            data={"status": False, "message": "Invalid OTP"},
                            status=status.HTTP_200_OK,
                        )
                else:
                    return Response(
                        data={"status": False, "message": "Invalid Data"},
                        status=status.HTTP_400_BAD_REQUEST,
                    )
            else:
                return Response(
                    data={"status": False, "message": "OTP or Mobile is None"},
                    status=status.HTTP_400_BAD_REQUEST,
                )
        except Exception as e:
            return Response(
                data={
                    "status": False,
                    "message": str(e),
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

    def send_password_reset_email(self, request):
        email = request.data.get("email", "")
        if User.objects.filter(email=email).exists():
            user = User.objects.filter(email=email).first()
            uidb64 = urlsafe_base64_encode(smart_bytes(user.id))
            token = PasswordResetTokenGenerator().make_token(user)
            # current_site = get_current_site(request=request.domain)
            relative_link = reverse(
                "password-reset-confirm", kwargs={"uidb64": uidb64, "token": token}
            )
            abs_url = "http://localhost:8000" + relative_link
            send_reset_password_email(email=email, link=abs_url)
        return Response(
            data={"status": True, "message": "Password reset link sent successfully."},
            status=status.HTTP_200_OK,
        )

    def reset_password(self, request, uidb64, token):
        try:
            print(request.data, uidb64, token)
            password = request.data.get("password", None)
            if password and (len(password) > 7):
                id = smart_str(urlsafe_base64_decode(uidb64))
                user = User.objects.get(id=int(id))
                if PasswordResetTokenGenerator().check_token(user, token):
                    user.set_password(password)
                    user.save()
                    return Response(
                        data={
                            "message": "Valid Credential, password reset successfully",
                            "uidb64": uidb64,
                            "token": token,
                        },
                        status=status.HTTP_200_OK,
                    )
                else:
                    return Response(
                        data={"message": "Invalid token"},
                        status=status.HTTP_401_UNAUTHORIZED,
                    )
            else:
                return Response(
                    data={"message": "Invalid Password Provided"},
                    status=status.HTTP_400_BAD_REQUEST,
                )
        except DjangoUnicodeDecodeError as e:
            return Response(
                data={"message": "Invalid token"}, status=status.HTTP_401_UNAUTHORIZED
            )


def user_details(request, id):
    user = get_object_or_404(User, id=id)
    context = {
        "user": user,
    }
    return render(request, "users/user-details.html", context)


def user_signup(request):
    form = UserRegistrationForm()
    context = {
        "form": form,
    }
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("users:login_page"))
        else:
            context = {
                "form": form,
            }

    return render(request, "users/signup.html", context)


def user_login(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse("venues:dashboard_overview"))
            else:
                print("USER is none")
    context = {
        "form": form,
    }
    return render(request, "users/login.html", context)


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse("users:login_page"))

templates/users/index.html
{% extends 'base.html' %}
{% block pagetitle %}
    Home Page
{% endblock%}
{% block content %}
    <h1> welcome</h1>
    {% for user in users %}
    <h5><a href="{% url 'user_details' user.id %}">{{user}}<a></h5>
    {% endfor %}
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block pagetitle %}
    Login Page
{% endblock pagetitle %}
    

{% block content %}
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form action="" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="exampleInputUsername" aria-describedby="usernameHelp"
                                                placeholder="Enter Username..." name="username" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password" name="password" required>
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember
                                                    Me</label>
                                            </div>
                                        </div>
                                        <input class="btn btn-primary btn-user btn-block" type="submit" value="Login">
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'users:password_reset' %}">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'users:signup_page' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
{% endblock content %}
    

templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %}
    Password Reset
{% endblock title %}


{% block content %}
    <h1> 
        Reset Password
    </h1>
    <p>
        Provide Email associated with your account
    </p>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Reset Password">
    </form>
{% endblock content %}
        

templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <p>You have successfully reset your password.</p>
    <a href="{% url 'users:login_page' %}">Login</a>
{% endblock content %}
    

templates/users/password_reset_confirm.html
{% extends 'base.html' %}


{% block content %}
    <h1>Change Password</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Confirm password">
    </form>
{% endblock content %}
    

templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
    <p>An Email has been sent, with instructions to reset your password.</p>
{% endblock content %}
    

templates/users/password_reset_email.html
<p> Follow this link to reset your password </p>
<a href="{{protocol}}:{{domain}}{% url 'users:password_reset_confirm' uidb64=uid token=token %}"> Reset Password</a>

{{protocol}}:{{domain}}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

templates/users/signup.html
{% extends 'base.html' %}
{% block pagetitle%}Register{% endblock %}
{% block content%}
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form action="" method="POST">
                                        {% csrf_token %}
                                        {{form.errors.as_p}}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="exampleInputUsername" aria-describedby="usernameHelp"
                                                placeholder="Enter Username..." name="username" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="EmailHelp"
                                                placeholder="Enter Email..." name="email" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="exampleInputMobile" aria-describedby="MobileHelp"
                                                placeholder="Enter Mobile..." name="mobile" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Enter Password" name="password1" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Confirm Password" name="password2" required>
                                        </div>
                                        <input class="btn btn-primary btn-user btn-block" type="submit" value="Sign Up">
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'users:password_reset' %}">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'users:login_page' %}">Already have an account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
{% endblock%}

templates/users/user-details.html
{% extends 'base.html' %}
{% block pagetitle %}
    {{user.username}}
{% endblock%}
{% block content %}
    <h1>{{user.username}}</h1>
    <ul class="list-unstyled">
        <li><b>Full Name : </b>{{user.name}}</li>
        <li><b>Phone : </b>{{user.mobile}}</li>
        <li><b>Email : </b>{{user.email}}</li>
    </ul>
{% endblock %}